"""create users_calendars join table

Revision ID: 8731335bff7e
Revises: faa97d3a70de
Create Date: 2022-12-21 18:32:24.495264

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")
# revision identifiers, used by Alembic.
revision = '8731335bff7e'
down_revision = 'faa97d3a70de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_calendars',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], name='fk_user_calendar_calendar_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_calendar_user_id'),
    sa.PrimaryKeyConstraint('user_id', 'calendar_id')
    )
    # ### end Alembic commands ###
    if environment == "production":
        op.execute(f"ALTER TABLE users_calendars SET SCHEMA {SCHEMA};")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_calendars')
    # ### end Alembic commands ###
