"""add owner_id col to calendars

Revision ID: 0f476c9cb511
Revises: a0dfacb86c88
Create Date: 2022-12-22 16:46:04.476241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f476c9cb511'
down_revision = 'a0dfacb86c88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_calendar_owner_id', 'users', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendars', schema=None) as batch_op:
        batch_op.drop_constraint('fk_calendar_owner_id', type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
