"""Drop users_calendars_join_table

Revision ID: 87fce594189f
Revises: 0f476c9cb511
Create Date: 2022-12-25 13:30:03.373595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87fce594189f'
down_revision = '0f476c9cb511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_calendars')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_calendars',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('calendar_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], name='fk_user_calendar_calendar_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_calendar_user_id'),
    sa.PrimaryKeyConstraint('user_id', 'calendar_id', name='users_calendars_pkey')
    )
    # ### end Alembic commands ###
