"""add_organiser_id_col_to_events

Revision ID: fdd5ede06778
Revises: dec8664d75ed
Create Date: 2023-01-16 12:45:44.225583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdd5ede06778'
down_revision = 'dec8664d75ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organiser_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_event_organiser_id', 'users', ['organiser_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_event_organiser_id', type_='foreignkey')
        batch_op.drop_column('organiser_id')

    # ### end Alembic commands ###
