"""create events_guests table

Revision ID: f17124067a7f
Revises: b01497358e86
Create Date: 2023-01-15 19:14:11.483340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f17124067a7f'
down_revision = 'b01497358e86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events_guests',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), server_default='awaiting', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='fk_event_guest_event_id'),
    sa.ForeignKeyConstraint(['guest_id'], ['users.id'], name='fk_event_guest_guest_id'),
    sa.PrimaryKeyConstraint('event_id', 'guest_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events_guests')
    # ### end Alembic commands ###
