"""add_guest_cols_to_events

Revision ID: dec8664d75ed
Revises: f17124067a7f
Create Date: 2023-01-15 19:17:09.774573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dec8664d75ed'
down_revision = 'f17124067a7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_modify_event', sa.BOOLEAN(), server_default='False', nullable=False))
        batch_op.add_column(sa.Column('guets_invite_others', sa.BOOLEAN(), server_default='True', nullable=False))
        batch_op.add_column(sa.Column('guest_see_guest_list', sa.BOOLEAN(), server_default='True', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('guest_see_guest_list')
        batch_op.drop_column('guets_invite_others')
        batch_op.drop_column('guest_modify_event')

    # ### end Alembic commands ###
